/*
 * three.java
 *
 * Created on __DATE__, __TIME__
 */

package add;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.ResultSet;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;

/**
 *
 * @author  __USER__
 */
public class three extends javax.swing.JFrame {

	/** Creates new form three */
	public three() {
		initComponents();
		int x, y;
		Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
		x = (size.width - 550) / 2;
		y = (size.height - 1000) / 2;
		setLocation(x, y);
		//让程序界面显示在屏幕中央
		setMinimumSize(new Dimension(250, 150));
		setDefaultCloseOperation(EXIT_ON_CLOSE);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel1.setForeground(new java.awt.Color(204, 0, 51));
		jLabel1.setText("\u4e70\u5bb6\u4fe1\u606f");

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/userName.png"))); // NOI18N
		jLabel2.setText("\u59d3\u540d");

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/email.png"))); // NOI18N
		jLabel3.setText("\u8054\u7cfb\u7535\u8bdd");

		jLabel4.setText("\u5bb6\u5ead\u4f4f\u5740");

		jLabel5.setText("\u7f16\u53f7");

		jButton1.setIcon(new javax.swing.ImageIcon(
				"F:\\Workspaces\\MyEclipse10\\petstore\\src\\images\\add.png")); // NOI18N
		jButton1.setText("\u786e\u8ba4");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel6.setText("\u5ba0\u7269\u4fe1\u606f");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jButton1)
																.addContainerGap())
												.addGroup(
														layout.createSequentialGroup()
																.addGap(61, 61,
																		61)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel5)
																								.addContainerGap())
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel3)
																												.addComponent(
																														jLabel2)
																												.addComponent(
																														jLabel4)
																												.addComponent(
																														jLabel6))
																								.addGap(69,
																										69,
																										69)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel1)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGap(10,
																																		10,
																																		10)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						jTextField2,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						117,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						jTextField3,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						117,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						jTextField4,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						117,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						jTextField5,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						117,
																																						Short.MAX_VALUE)))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGap(10,
																																		10,
																																		10)
																																.addComponent(
																																		jTextField1,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		117,
																																		Short.MAX_VALUE)))
																								.addGap(141,
																										141,
																										141)))))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addGap(15, 15, 15)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(44, 44, 44)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														jTextField2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(39, 39, 39)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(
														jTextField3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(45, 45, 45)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jTextField4,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel6))
								.addGap(48, 48, 48)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel5)
																.addGap(47, 47,
																		47)
																.addComponent(
																		jButton1))
												.addComponent(
														jTextField5,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(42, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Connection conn = null;
		Statement st = null;
		ResultSet rs = null;
		try {
			//注册驱动
			Class.forName("com.mysql.jdbc.Driver");
			//建立连接
			conn = (Connection) DriverManager.getConnection(
					"jdbc:mysql://localhost:3306/pet", "root", "admin");
			//3.创建语句
			st = (Statement) conn.createStatement();

			String sql = "insert into three(购买人,联系电话,家庭住址,宠物信息,购买时间) values('"
					+ this.jTextField1.getText() + "','"
					+ this.jTextField2.getText() + "','"
					+ this.jTextField3.getText() + "','"
					+ this.jTextField4.getText() + "',now())";

			//System.out.println("i=" + i);
			st.executeUpdate(sql);
			st.executeQuery("select * from three");
			st = (Statement) conn.createStatement();
			String a = this.jTextField5.getText();
			String sql1 = "delete from one where 编号='" + a + "'";
			st.executeUpdate(sql1);
			System.out.print("操作成功!");
		} catch (Exception e) {
			System.out.print("操作失败!");
			e.printStackTrace();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new three().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	// End of variables declaration//GEN-END:variables

}