/*
 * rtwo.java
 *
 * Created on __DATE__, __TIME__
 */

package refer;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
/*
 * refer5.java
 *
 * Created on __DATE__, __TIME__
 */
import java.util.Vector;

import add.three;

/**
 *
 * @author  __USER__
 */
public class rtwo extends javax.swing.JFrame {

	/** Creates new form rtwo */
	public rtwo() {
		initComponents();
		int x, y;
		Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
		x = (size.width - 950) / 2;
		y = (size.height - 600) / 2;
		setLocation(x, y);
		//让程序界面显示在屏幕中央
		setMinimumSize(new Dimension(250, 150));
		setDefaultCloseOperation(EXIT_ON_CLOSE);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jComboBox1 = new javax.swing.JComboBox();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null } },
				new String[] { "编号", "名字", "宠物种类", "性别", "年龄", "入库时间", "疾病史",
						"过敏史", "疫苗记录" }));
		jScrollPane1.setViewportView(jTable1);

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"全部查询", "大于等于", "小于等于", "关键字（名字）", "编号" }));

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/search.png"))); // NOI18N
		jButton1.setText("\u786e\u8ba4");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u8d2d\u4e70");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(49, 49, 49)
								.addComponent(jButton2)
								.addGap(119, 119, 119)
								.addComponent(jComboBox1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(34, 34, 34)
								.addComponent(jTextField1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										152,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										129, Short.MAX_VALUE)
								.addComponent(jButton1).addGap(42, 42, 42))
				.addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										layout.createSequentialGroup()
												.addContainerGap()
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														777,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap(
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(485, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jComboBox1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jButton1)
												.addComponent(jButton2))
								.addGap(28, 28, 28))
				.addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										layout.createSequentialGroup()
												.addContainerGap()
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap(
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		three fm = new three();
		fm.show();
		fm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		Vector data = new Vector();
		Vector<Object> v = new Vector();
		Vector names = new Vector();
		names.add("编号");
		names.add("名字");
		names.add("宠物种类");
		names.add("性别");
		names.add("年龄");
		names.add("入库时间");
		names.add("疾病史");
		names.add("过敏史");
		names.add("疫苗记录");

		Connection conn = null;
		Statement st = null;
		ResultSet rs = null;

		try {
			//注册驱动
			Class.forName("com.mysql.jdbc.Driver");
			//建立连接
			conn = DriverManager.getConnection(
					"jdbc:mysql://localhost:3306/pet", "root", "admin");
			//3.创建语句
			st = conn.createStatement();
			if (this.jComboBox1.getSelectedIndex() == 0) {
				rs = st.executeQuery("select * from one natural join two");
			}
			if (this.jComboBox1.getSelectedIndex() == 1) {
				rs = st.executeQuery("select * from one natural join two where 年龄>='"
						+ this.jTextField1.getText() + "'");
			}
			if (this.jComboBox1.getSelectedIndex() == 2) {
				rs = st.executeQuery("select * from one natural join two where 年龄<='"
						+ this.jTextField1.getText() + "'");
			}
			if (this.jComboBox1.getSelectedIndex() == 3) {
				rs = st.executeQuery("select * from one natural join two where 名字 like'"
						+ this.jTextField1.getText() + "%'");
			}
			if (this.jComboBox1.getSelectedIndex() == 4) {
				rs = st.executeQuery("select * from one natural join two where 编号 ='"
						+ this.jTextField1.getText() + "%'");
			}
			//4.执行语句
			//5.处理结果 
			while (rs.next()) {
				System.out.println(rs.getString(1) + "\t" + rs.getObject(2)
						+ "\t" + rs.getObject(3) + "\t" + rs.getObject(4)
						+ "\t" + rs.getObject(5) + "\t" + rs.getObject(6)
						+ "\t" + rs.getObject(7) + "\t" + rs.getObject(8)
						+ "\t" + rs.getObject(9));

				v.clear();
				v.add(rs.getString(1));
				v.add(rs.getString(2));
				v.add(rs.getString(3));
				v.add(rs.getString(4));
				v.add(rs.getString(5));
				v.add(rs.getString(6));
				v.add(rs.getString(7));
				v.add(rs.getString(8));
				v.add(rs.getString(9));
				data.add(v.clone());
				jTable1.setModel(new javax.swing.table.DefaultTableModel(data,
						names));

			}
		} catch (Exception e) {
			System.out.print("get data error!");
			e.printStackTrace();
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new rtwo().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}